import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

//Components
import Header from "@/components/ui/Header";
import PageTransition from "@/components/ui/PageTransition";


const JetBrainsMono = JetBrains_Mono({
  subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-jetbrainsMono',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${JetBrainsMono.variable}`}>
        
        <PageTransition>
        <Header/>  
          {children}
        </PageTransition>      
      </body>
    </html>
  );
}
